# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems:			  [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Alisher Tortay
tagline:          Computer Science student at KAIST
description:      Computer Science student at KAIST
#url:              http://hyde.getpoole.com
url:			  http://alishertortay.me
baseurl:          /

author:
  name:           'Alisher Tortay'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
  repo:			  https://github.com/Chizhik
